### ISSUE TITLE
Error response from daemon: client version 1.36 is too new. Maximum supported API version is 1.34

### ISSUE THREAD

**Issue by markcallen** [markcallen/deezee#1]
When running with a new version of docker:

````
docker --version
Docker version 17.11.0-ce-rc4, build 587f1f0
````

````
deezee run --file=sync.yml 
Process: synctosolarch
	Globals:
	Task: awssync
panic: Error response from daemon: client version 1.36 is too new. Maximum supported API version is 1.34

goroutine 1 [running]:
main.(*Task).getImage(0xc4201e7dc8)
	/Users/marka/go/src/github.com/markcallen/deezee/task.go:64 +0x4ec
main.(*Task).Run(0xc4201e7dc8, 0x2b, 0xc4200d3d70)
	/Users/marka/go/src/github.com/markcallen/deezee/task.go:43 +0xa6
main.(*Process).Run(0xc4201e7f20, 0x0)
	/Users/marka/go/src/github.com/markcallen/deezee/process.go:107 +0x7d2
main.main()
	/Users/marka/go/src/github.com/markcallen/deezee/deezee.go:56 +0x1f5
````

**Comment by markcallen** [comment]
Some version of the docker library do not allow older clients to connect to it.

Set the DOCKER_API_VERSION environment variable before running the command:

````
DOCKER_API_VERSION=1.34 deezee run --file=sync.yml
````
